### ISSUE TITLE
Framework Bundle should go into Infrastructure Layer

### ISSUE THREAD

**Issue by ghost** [regniblod/symfony-standard-ddd#1]
Framework Bundle and framework specific stuff should go into Infrastructure Layer.

**Why**
From http://dddsample.sourceforge.net/architecture.html **Infrastructure:** *It handles interpretation, validation and translation of incoming data. It also handles serialization of outgoing data, such as HTML or XML across HTTP to web browsers or web service clients*
**Application Layer:** *The application layer is thin in terms of domain logic - it merely coordinates the domain layer objects to perform the actual work.*
I think what it should belong to Application layer is not more than Controllers (usually also Commands in a command bus driven approach) that are responsible for coordinating the objects and the workflow for the application.
In Symfony also, the bundle is used as a standard place for doctrine schema generation, Doctrine Repositories, Views (which should not be part of the application Layer).
And as I see from your structure, we have to do, kind of work-around for doctrine mappings located out of the Bundle scope.

**Usecase** https://github.com/mathiasverraes/symfony-live-2014/tree/master/src/Infrastructure/LessonScheduleBundle this is a scaffolding from Mathias Verraes DDD workshop just as a comproving example

I'm going to find and provide some more authoritative sources and examples.
What do you think? :)

**Comment by ghost** [comment]
From [Eric Evans - Domain Driven Design - Tackling complexity in the heart of software](https://www.amazon.com/Domain-Driven-Design-Tackling-Complexity-Software/dp/0321125215)

**Chapter - Layered Architecture**
> **Infrastructure** Provides generic technical capabilities that support the higher layers: message sending for the application, persistence for the domain, drawing widgets for the UI, and so on. The infrastructure layer may also support the pattern of interactions between the four layers through an architectural framework.

**Comment by linkcotech** [comment]
@0x13a None of the examples Eric mentions is framework integration :)
In simple term you can think of infrastructure as the touch point for any external communication.
